[package]
name = "prate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
rowan = "0.15.8"
num-derive = "0.3.3"
num-traits = "0.2.15"
expect-test = "1.4.0"
drop_bomb = "0.1.5"